ARG version
FROM almalinux
ENV course="DevOps" \
    duration="120 hr" 
ARG trainer="kalyan"
RUN echo "hi, course is: ${course}, duration is: ${duration}, trainer is: ${trainer}"
CMD [ "sleep", "999" ]